In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import patsy

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RidgeCV
%matplotlib inline

## Read in data

In [4]:
#Import Joshua Tree routes
jtree_boulder = pd.read_csv('jtree_boulder.csv')
jtree_rock = pd.read_csv('CA_JTree_Routes_Rock_250.csv')
#Import Red Rocks routes
redrocks_boulder = pd.read_csv('redrocks_boulder.csv')
redrocks_rock = pd.read_csv('redrocks_rock.csv')
#Import CA Aid Routes
ca_aid = pd.read_csv('ca_aid.csv')
#Import Sierra East Routes
sierraeast_boulder = pd.read_csv('sierra_east_boulder.csv')
sierraeast_rock = pd.read_csv('sierra_east_rock.csv')
#Import Yosemite Routes
yosemite_boulder = pd.read_csv('yosemite_boulder.csv')
yosemite_rock = pd.read_csv('yosemite_rock.csv')

frames = [jtree_boulder, jtree_rock, redrocks_boulder, redrocks_rock, ca_aid, 
          sierraeast_boulder, sierraeast_rock, yosemite_boulder, yosemite_rock]

df = pd.concat(frames)

df.head()

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,sub_area,photos,comments,near_grades,aid_grade
0,Todd Gordon Memorial Chossy Pile of Radness (a...,2.5,6,5.11b,"['Sport', 'TR', 'Boulder']",35.0,1,NaN,NaN,California,Rattlesnake Canyon,2,7,"['5.10a', '5.9', '5.9', '5.11a/b', '5.7', 'V2+']",NaN
1,A Hearty Handful of Cheek,2.0,2,V0,['Boulder'],6.0,1,PG13,NaN,California,Group Campsites Rd,1,0,[],NaN
2,Gait of Power Traverse,2.0,1,V1,['Boulder'],20.0,1,NaN,NaN,California,Indian Cove Cam…,0,0,"['5.9', '5.10a', '5.11c', 'V1-2', '5.8-', '5.1...",NaN
3,Crack Alley,2.0,8,V1-2,['Boulder'],15.0,1,NaN,NaN,California,Indian Cove Cam…,3,0,"['5.9', '5.10a', '5.11c', '5.8-', '5.10a/b', '...",NaN
4,Fart Man,2.0,2,V1,['Boulder'],15.0,1,NaN,NaN,California,Indian Cove Cam…,0,0,"['5.5', '5.9', '5.8', '5.5', '5.0', '5.9', '5....",NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5985 entries, 0 to 989
Data columns (total 15 columns):
name           5985 non-null object
rating         5985 non-null float64
votes          5985 non-null int64
grade          5979 non-null object
type           5985 non-null object
height         5291 non-null float64
pitches        5985 non-null int64
safety         735 non-null object
commitment     414 non-null object
state          5985 non-null object
sub_area       5985 non-null object
photos         5985 non-null int64
comments       5985 non-null int64
near_grades    5985 non-null object
aid_grade      170 non-null object
dtypes: float64(2), int64(4), object(9)
memory usage: 748.1+ KB

In [6]:
#Shuffle the data frame. Frac=1 means all rows
df = df.sample(frac=1).reset_index(drop=True)

df.head()

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,sub_area,photos,comments,near_grades,aid_grade
0,Going Both Ways,3.5,17,5.11c,"['Sport', 'Alpine']",60.0,1,NaN,NaN,California,Dike Wall,1,0,"['5.11a', '5.11d', '5.11b', '5.11b', '5.10c', ...",NaN
1,Too Close for Comfort,2.0,2,5.11d,['Sport'],40.0,1,NaN,NaN,California,Main Island,0,0,"['5.10a', '5.10a', '5.6', '5.8', '5.10b', '5.1...",NaN
2,Victim of AIDS,3.1,22,5.12a,"['Trad', 'TR', 'Aid']",25.0,1,NaN,NaN,California,Mt Woodson,1,5,"['5.8', '5.7', '5.8', '5.10a']",NaN
3,Christmas in July,2.4,8,5.10b/c,['Sport'],100.0,1,NaN,NaN,California,Rock Creek,1,0,"['5.10', '5.10c', '5.10d', '5.11', '5.10b', '5...",NaN
4,Bridge of Sighs,2.8,4,5.11a,['Trad'],50.0,1,R,NaN,California,Rattlesnake Canyon,0,1,[],NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5985 entries, 0 to 5984
Data columns (total 15 columns):
name           5985 non-null object
rating         5985 non-null float64
votes          5985 non-null int64
grade          5979 non-null object
type           5985 non-null object
height         5291 non-null float64
pitches        5985 non-null int64
safety         735 non-null object
commitment     414 non-null object
state          5985 non-null object
sub_area       5985 non-null object
photos         5985 non-null int64
comments       5985 non-null int64
near_grades    5985 non-null object
aid_grade      170 non-null object
dtypes: float64(2), int64(4), object(9)
memory usage: 701.5+ KB

## Pre-Processing

### Cleaning: Removing Duplicates, Outliers, Unnecessary Data, Etc.

In [8]:
#Remove duplicates
def remove_duplicates(df):
    df.drop_duplicates(keep = 'first',inplace=True)

remove_duplicates(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5970 entries, 0 to 5984
Data columns (total 15 columns):
name           5970 non-null object
rating         5970 non-null float64
votes          5970 non-null int64
grade          5964 non-null object
type           5970 non-null object
height         5278 non-null float64
pitches        5970 non-null int64
safety         730 non-null object
commitment     409 non-null object
state          5970 non-null object
sub_area       5970 non-null object
photos         5970 non-null int64
comments       5970 non-null int64
near_grades    5970 non-null object
aid_grade      166 non-null object
dtypes: float64(2), int64(4), object(9)
memory usage: 746.2+ KB

In [9]:
df.rating.describe()

count    5970.000000
mean        2.291055
std         0.875460
min         0.000000
25%         1.800000
50%         2.300000
75%         3.000000
max         4.000000
Name: rating, dtype: float64

In [10]:
df.rating.isna().sum()

0

In [11]:
df.votes.describe()

count    5970.000000
mean       17.683250
std        57.647347
min         0.000000
25%         1.000000
50%         3.000000
75%        12.000000
max      1469.000000
Name: votes, dtype: float64

In [12]:
#Remove voting outliers
def remove_outliers(df):
    #Remove rows with over 1000 votes
    high_votes = (df.loc[df.votes > 500]).index
    df.drop(index = high_votes, inplace = True)
    
    #Remove rows with less than 1 vote
    low_votes = (df.loc[df.votes < 1]).index
    df.drop(index = low_votes, inplace = True)    
    
remove_outliers(df)
df.describe()

,rating,votes,height,pitches,photos,comments
count,5899.000000,5899.000000,5236.000000,5899.000000,5899.000000,5899.000000
mean,2.311341,16.071877,135.691367,1.628412,2.057128,1.780641
std,0.848068,40.084980,319.343940,2.456039,4.289059,4.023586
min,0.000000,1.000000,4.000000,1.000000,0.000000,0.000000
25%,1.800000,1.000000,15.000000,1.000000,0.000000,0.000000
50%,2.300000,3.000000,50.000000,1.000000,1.000000,0.000000
75%,3.000000,12.000000,100.000000,1.000000,2.000000,2.000000
max,4.000000,496.000000,4700.000000,35.000000,116.000000,72.000000

In [13]:
def remove_noGrade(df):
    """Remove rows that have no grade listed."""
    df.dropna(subset=['grade'], inplace = True)

remove_noGrade(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5893 entries, 0 to 5984
Data columns (total 15 columns):
name           5893 non-null object
rating         5893 non-null float64
votes          5893 non-null int64
grade          5893 non-null object
type           5893 non-null object
height         5230 non-null float64
pitches        5893 non-null int64
safety         720 non-null object
commitment     398 non-null object
state          5893 non-null object
sub_area       5893 non-null object
photos         5893 non-null int64
comments       5893 non-null int64
near_grades    5893 non-null object
aid_grade      158 non-null object
dtypes: float64(2), int64(4), object(9)
memory usage: 736.6+ KB

In [14]:
def remove_noHeight(df):
    """Remove rows that have no height."""
    df.dropna(subset=['height'], inplace = True)

remove_noHeight(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5230 entries, 0 to 5984
Data columns (total 15 columns):
name           5230 non-null object
rating         5230 non-null float64
votes          5230 non-null int64
grade          5230 non-null object
type           5230 non-null object
height         5230 non-null float64
pitches        5230 non-null int64
safety         667 non-null object
commitment     357 non-null object
state          5230 non-null object
sub_area       5230 non-null object
photos         5230 non-null int64
comments       5230 non-null int64
near_grades    5230 non-null object
aid_grade      143 non-null object
dtypes: float64(2), int64(4), object(9)
memory usage: 653.8+ KB

In [15]:
def wrong_commitment(row):
    """Remove rows where a boulder has a commitment grade 'V'."""
    num_types = len(row['type'].split())
    name_type = row['type'].split()[0].replace('[', '').replace("'", '').replace(']', '')
    if (row['commitment'] == 'V') and (num_types == 1) and (name_type == 'Boulder'):
        df.drop(index = row.name, inplace = True)
    
df.apply(lambda row: wrong_commitment(row), axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5227 entries, 0 to 5984
Data columns (total 15 columns):
name           5227 non-null object
rating         5227 non-null float64
votes          5227 non-null int64
grade          5227 non-null object
type           5227 non-null object
height         5227 non-null float64
pitches        5227 non-null int64
safety         666 non-null object
commitment     354 non-null object
state          5227 non-null object
sub_area       5227 non-null object
photos         5227 non-null int64
comments       5227 non-null int64
near_grades    5227 non-null object
aid_grade      143 non-null object
dtypes: float64(2), int64(4), object(9)
memory usage: 653.4+ KB

In [16]:
def split_it(row):
    """Standardize type column by removing brackets, spaces, and quotation marks"""
    split_row = row['type'].replace('[', '').replace(']', '').replace("'", '').replace(' ', '')
    return split_row.split(',')

df['type'] = df.apply(lambda row: split_it(row), axis=1)

### Converting Categorical Data to Numerical Data

In [17]:
import re

In [18]:
#Calculate Popularity
def popularity2(row):
    """
    bayesian rating = (v ÷ (v+m)) × R + (m ÷ (v+m)) × C 
    where:
    R = average for the anime
    v = number of votes for the anime
    m = minimum votes required to be listed (currently 12)
    C = the mean vote across the whole report (currently 7.5017)
    source: https://www.animenewsnetwork.com/encyclopedia/ratings-anime.php#best_bayesian
    """
    R = row.rating 
    C = df.rating.mean()
    V = row.votes
    M = 1
    popularity = ((V / (V+M)) * R) + (M / (V+M)) * C
    return popularity

#Apply the popularity function to every row and add it to a column named 'popularity'
df['popularity'] = df.apply(lambda row: popularity2(row), axis=1)
df.popularity.describe()

count    5227.000000
mean        2.342199
std         0.622392
min         0.698971
25%         1.848713
50%         2.298713
75%         2.749485
max         3.996053
Name: popularity, dtype: float64

In [19]:
#Calculate Difficulty
def combined_difficulty(row):
    """
    Integer to represent general climbing difficulty, combining all types of climbing.
    Source: https://rockclimbingforwomen.com/climbing-grade-comparison-bouldering-vs-sport-climbing-equivalent
    """
    if type(row) == str:
        grade = row
    else:
        grade = row.grade
    if(grade == None):
        difficulty = None
        return difficulty
    elif (re.search('5.15d', grade) or re.search('V16', grade)):
        difficulty = 18
    elif ( re.search('5.15c', grade) or re.search('V15', grade)):
        difficulty = 17
    elif (re.search('5.15b', grade) or re.search('V14', grade)):
        difficulty = 16
    elif (re.search('V15', grade)):
        difficulty = 15
    elif (re.search('5.15a', grade) or re.search('V12', grade)):
        difficulty = 14
    elif (re.search('5.14d', grade) or re.search('V11', grade)):
        difficulty = 13
    elif (
        re.search('5.14b', grade) or re.search('5.14c', grade) or 
        re.search('V10', grade) or re.search('5.14+', grade)
    ):
        difficulty = 12
    elif (re.search('5.14a', grade) or re.search('V9', grade)):
        difficulty = 11
    elif (re.search('5.13d', grade) or re.search('V8', grade)):
        difficulty = 10
    elif (re.search('5.13c', grade) or re.search('V7', grade)):
        difficulty = 9
    elif (
            re.search('5.13a', grade) or re.search('5.13b', grade) or 
            re.search('V6', grade) or re.search('5.13-', grade)
    ):
        difficulty = 8
    elif (
            re.search('5.12a', grade) or re.search('5.12b', grade) or 
            re.search('V4', grade) or re.search('5.12-', grade)
    ):
        difficulty = 6    
    elif (
            re.search('5.12c', grade) or re.search('5.12d', grade) or 
            re.search('V5', grade) or re.search('5.12+', grade)
    ):
        difficulty = 7
    elif (
            re.search('5.11a', grade) or re.search('5.11b', grade) or 
            re.search('V2', grade) or re.search('5.11-', grade)
    ):
        difficulty = 4    
    elif (
            re.search('5.11c', grade) or re.search('5.11d', grade) or 
            re.search('V3', grade) or re.search('5.11+', grade)
    ):
        difficulty = 5

    elif (
            re.search('5.7', grade) or re.search('5.8', grade) or 
            re.search('5.9', grade) or re.search('5.10a', grade) or 
            re.search('5.10b', grade) or re.search('V0', grade) or
            re.search('5.10-', grade)
    ):
        difficulty = 2
    elif (
            re.search('5.10c', grade) or re.search('5.10d', grade) or 
            re.search('V1', grade) or re.search('5.10+', grade)
    ):
        difficulty = 3
    elif (
            re.search('5.0', grade) or re.search('5.1', grade) or 
            re.search('5.2', grade) or re.search('5.3', grade) or 
            re.search('5.4', grade) or re.search('5.5', grade) or
            re.search('5.6', grade) or re.search('VB', grade) or
            re.search('V-easy', grade) or re.search('3rd', grade) or
            re.search('4th', grade) or re.search('5th', grade) or
            re.search('Easy', grade)
    ):
        difficulty = 1
    else:
        difficulty = None

    return difficulty

df['combined_difficulty'] = df.apply(lambda row: combined_difficulty(row), axis=1)
df.head()

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,sub_area,photos,comments,near_grades,aid_grade,popularity,combined_difficulty
0,Going Both Ways,3.5,17,5.11c,"[Sport, Alpine]",60.0,1,NaN,NaN,California,Dike Wall,1,0,"['5.11a', '5.11d', '5.11b', '5.11b', '5.10c', ...",NaN,3.433047,5
1,Too Close for Comfort,2.0,2,5.11d,[Sport],40.0,1,NaN,NaN,California,Main Island,0,0,"['5.10a', '5.10a', '5.6', '5.8', '5.10b', '5.1...",NaN,2.098285,5
2,Victim of AIDS,3.1,22,5.12a,"[Trad, TR, Aid]",25.0,1,NaN,NaN,California,Mt Woodson,1,5,"['5.8', '5.7', '5.8', '5.10a']",NaN,3.064994,6
3,Christmas in July,2.4,8,5.10b/c,[Sport],100.0,1,NaN,NaN,California,Rock Creek,1,0,"['5.10', '5.10c', '5.10d', '5.11', '5.10b', '5...",NaN,2.388317,2
4,Bridge of Sighs,2.8,4,5.11a,[Trad],50.0,1,R,NaN,California,Rattlesnake Canyon,0,1,[],NaN,2.698971,4

In [20]:
#Calculate Difficulty
def difficulty_sport_trad(row):
    """
    Integer to represent general climbing difficulty, combining all types of climbing.
    Source: https://rockclimbingforwomen.com/climbing-grade-comparison-bouldering-vs-sport-climbing-equivalent
    """
    grade = row.grade
    if (re.search('5.15', grade)):
        difficulty = 22
    elif (re.search('5.14', grade)):
        difficulty = 21
    elif (re.search('5.13c', grade)):
        difficulty = 20
    elif (re.search('5.13b', grade)):
        difficulty = 19
    elif (re.search('5.13a', grade) or re.search('5.13', grade)):      
        difficulty = 18
    elif (re.search('5.12c', grade)):
        difficulty = 17
    elif (re.search('5.12b', grade)):
        difficulty = 16
    elif (re.search('5.12a', grade) or re.search('5.12', grade)):      
        difficulty = 15
    elif (re.search('5.11d', grade)):
        difficulty = 14
    elif (re.search('5.11c', grade)):
        difficulty = 13
    elif (re.search('5.11b', grade)):
        difficulty = 12
    elif (re.search('5.11a', grade) or re.search('5.11', grade)):
        difficulty = 11
    elif (re.search('5.10d', grade)):
        difficulty = 10
    elif (re.search('5.10c', grade)):
        difficulty = 9
    elif (re.search('5.10b', grade)):
        difficulty = 8
    elif (re.search('5.10a', grade) or re.search('5.10', grade)):
        difficulty = 7
    elif (re.search('5.9', grade)):
        difficulty = 6
    elif (re.search('5.8', grade)):
        difficulty = 5
    elif (re.search('5.7', grade)):
        difficulty = 4
    elif (re.search('5.6', grade)):
        difficulty = 3
    elif (re.search('5.5', grade)):
        difficulty = 2
    elif (
            re.search('5.0', grade) or re.search('5.1', grade) or 
            re.search('5.2', grade) or re.search('5.3', grade) or 
            re.search('5.4', grade) or re.search('3rd', grade) or
            re.search('4th', grade) or re.search('5th', grade) or
            re.search('Easy', grade)
    ):
        difficulty = 1

    else:
        difficulty = None

    return difficulty

df['difficulty_sport_trad'] = df.apply(lambda row: difficulty_sport_trad(row), axis=1)
print(df[['difficulty_sport_trad', 'type', 'grade']])

      difficulty_sport_trad             type    grade
0                      13.0  [Sport, Alpine]    5.11c
1                      14.0          [Sport]    5.11d
2                      15.0  [Trad, TR, Aid]    5.12a
3                       8.0          [Sport]  5.10b/c
4                      11.0           [Trad]    5.11a
...                     ...              ...      ...
5980                    8.0           [Trad]    5.10b
5981                   16.0          [Sport]    5.12b
5982                    NaN        [Boulder]   V-easy
5983                    NaN        [Boulder]       V6
5984                    5.0          [Sport]      5.8

[5227 rows x 3 columns]

In [21]:
def num_near_grades(row):
    """Finds the number of routes in close proximity to this route."""
    if row.near_grades == '[]':
        num_grades = 0
        return num_grades
    num_grades_list = row.near_grades.split()
    num_grades = len(num_grades_list)
    return num_grades

df['number_near_grades'] = df.apply(lambda row: num_near_grades(row), axis=1)
df

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,sub_area,photos,comments,near_grades,aid_grade,popularity,combined_difficulty,difficulty_sport_trad,number_near_grades
0,Going Both Ways,3.5,17,5.11c,"[Sport, Alpine]",60.0,1,NaN,NaN,California,Dike Wall,1,0,"['5.11a', '5.11d', '5.11b', '5.11b', '5.10c', ...",NaN,3.433047,5,13.0,13
1,Too Close for Comfort,2.0,2,5.11d,[Sport],40.0,1,NaN,NaN,California,Main Island,0,0,"['5.10a', '5.10a', '5.6', '5.8', '5.10b', '5.1...",NaN,2.098285,5,14.0,6
2,Victim of AIDS,3.1,22,5.12a,"[Trad, TR, Aid]",25.0,1,NaN,NaN,California,Mt Woodson,1,5,"['5.8', '5.7', '5.8', '5.10a']",NaN,3.064994,6,15.0,4
3,Christmas in July,2.4,8,5.10b/c,[Sport],100.0,1,NaN,NaN,California,Rock Creek,1,0,"['5.10', '5.10c', '5.10d', '5.11', '5.10b', '5...",NaN,2.388317,2,8.0,16
4,Bridge of Sighs,2.8,4,5.11a,[Trad],50.0,1,R,NaN,California,Rattlesnake Canyon,0,1,[],NaN,2.698971,4,11.0,0
5,Smooth as a Baby's Ass,1.7,3,V2,[Boulder],13.0,1,NaN,NaN,California,Indian Wave Bou…,1,0,"['V-easy', 'V-easy', 'V0-']",NaN,1.848713,4,NaN,3
6,Crystalline Ceilidh,1.0,1,5.10a/b,"[Sport, Alpine]",45.0,1,NaN,NaN,California,Crystal Crag,0,0,"['5.11d', '5.9', '5.11d']",NaN,1.647427,2,7.0,3
7,Maltese Falcon,3.5,31,5.12a,[Sport],50.0,1,NaN,NaN,California,Main Island,2,1,"['5.8', '5.12d']",NaN,3.462339,6,15.0,2
8,BamBam,1.3,3,5.10a,[Sport],25.0,1,NaN,NaN,California,Little Egypt,0,1,"['5.10a', '5.6', '5.11', '5.11+', '5.9']",NaN,1.548713,2,7.0,5
9,Kids of the Black Hole,1.5,2,V0,[Boulder],12.0,1,NaN,NaN,California,Love Nest Area,2,0,"['V-easy', 'V-easy', 'V4']",NaN,1.764951,2,NaN,3
11,Eddie Muenster,2.1,14,5.7,"[Trad, Sport]",100.0,1,NaN,NaN,California,Cottage Domes,1,0,"['5.5', 'Easy 5th', '5.8', '5.6', '5.8']",NaN,2.112990,2,4.0,6
12,The Forgotten Route II,2.0,1,5.11-,[Trad],145.0,1,R,NaN,California,Rock Creek,0,0,"['5.10+', '5.10+', '5.9', '5.11', '5.10+', '5....",NaN,2.147427,4,11.0,14
13,Krusty’s Korner,2.0,1,5.8,[Sport],60.0,1,NaN,NaN,California,Sherwin Plateau,1,0,"['5.9+', '5.8', '5.8+', '5.7', '5.10-', '5.7',...",NaN,2.147427,2,5.0,25
14,Arete to Arete,2.7,29,V3,[Boulder],20.0,1,PG13,NaN,California,Rock Creek Boul…,4,5,"['V9', 'V6', 'V6', 'V10', 'V0', 'V0-', 'V4', '...",NaN,2.686495,5,NaN,10
16,Tilt-o-Meter Traverse,3.0,1,V1,[Boulder],20.0,1,NaN,NaN,California,Outback Bouldering,0,0,"['V2', 'V4', 'V1', 'V1+', 'V1']",NaN,2.647427,3,NaN,5
19,Guano Hold Your Hand,3.0,1,5.10c,[Sport],60.0,1,NaN,NaN,California,Rock Creek,1,0,"['5.11b', '5.10-', '5.8', '5.10', '5.12+', '5....",NaN,2.647427,3,9.0,10
20,Flaky Face Left,2.0,1,V3,[Boulder],15.0,1,NaN,NaN,California,Razor Back Area,2,0,['V4'],NaN,2.147427,5,NaN,1
22,Left White Face,2.0,1,5.8+,[TR],80.0,1,NaN,NaN,California,Silver Lake,1,0,"['5.7', '5.7+', '5.8', '5.4', '5.3', '5.9+', '...",NaN,2.147427,2,5.0,7
23,Shiner,3.4,5,5.11b/c,[Sport],60.0,1,NaN,NaN,California,Medlicott Dome,0,1,"['5.11a', '5.11c', '5.11b', '5.10b', '5.9', '5...",NaN,3.215809,4,12.0,21
24,Low Slab Direct,2.0,1,5.4,[TR],80.0,1,NaN,NaN,California,Silver Lake,1,0,"['5.7', '5.7+', '5.8+', '5.8', '5.3', '5.9+', ...",NaN,2.147427,1,1.0,7
25,Once the Bullet Leaves...,1.3,3,V0,[Boulder],15.0,1,NaN,NaN,California,S - Pocket Rock…,1,0,"['V0+', 'V0']",NaN,1.548713,2,NaN,2
26,North Crack,2.5,2,V2,[Boulder],20.0,1,PG13,NaN,California,Fault Line,2,0,"['V1-', 'V0+', 'V0']",NaN,2.431618,4,NaN,3
27,Open Your Eyes,4.0,2,5.11c,[Trad],110.0,1,NaN,NaN,California,p. Reed's Pinna…,0,1,"['5.9-', '5.10+', '5.11c', '5.10c', '5.9', '5....",NaN,3.431618,5,13.0,37
28,The Sanga's On Fire,2.5,6,5.10a,[Trad],160.0,2,NaN,NaN,California,Valley of Kings,2,6,"['5.7', '5.8', '5.10d']",NaN,2.470693,2,7.0,3
30,Vino Rojo,3.8,105,V6,[Boulder],15.0,1,NaN,NaN,Nevada,Kraft Boulders,6,4,"['V5+', 'V8', 'V2', 'V8', 'V4', 'V6']",NaN,3.785801,8,NaN,6
31,Crankcase,1.8,14,V3,[Boulder],11.0,1,NaN,NaN,California,Manx Boulders,1,2,"['V2', 'V1', 'V0', 'V-easy', 'V4', 'V2+', 'V0-...",NaN,1.832990,5,NaN,10
34,Black Dihedral,3.3,53,5.10b,"[Trad, Alpine]",70.0,1,NaN,NaN,California,Dike Wall,2,6,"['5.11b', '5.10c/d', '5.10a', '5.10b', '5.11c'...",NaN,3.281386,2,8.0,7
36,Bombs over Tokyo (1st pitch),3.8,157,5.10c,[Trad],105.0,1,NaN,NaN,California,Daff Dome,6,14,"['5.11a', '5.9', '5.12+', '5.11a', '5.10a', '5...",NaN,3.790474,3,9.0,15
37,Chips Ahoy,3.5,2,5.12b,[Sport],100.0,1,NaN,NaN,California,h. Cookie Area,0,0,"['5.11b', '5.10b', '5.10a', '5.11c', '5.11a', ...",NaN,3.098285,6,16.0,34
38,Honeycomb Chimney,2.7,38,5.9,[Trad],800.0,8,NaN,III,Nevada,Magic Mountain,35,13,"['5.10c', '5.8', '5.9+', '5.9', '5.10', '5.10'...",NaN,2.689612,2,6.0,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5951,Cotton Headed Ninny Muggins,3.0,1,5.10b,[Trad],160.0,1,NaN,NaN,California,Rock Creek,2,0,"['5.10a/b', '5.10d', '5.11a/b', '5.8', '5.9', ...",NaN,2.647427,2,8.0,8
5952,Problem D,1.0,2,V-easy,[Boulder],12.0,1,NaN,NaN,California,Outback Bouldering,0,0,"['V0', 'V0', 'V-easy', 'V-easy', 'V0', 'V3']",NaN,1.431618,1,NaN,6
5953,"We Aim To Please, So, Please Aim",1.5,2,5.7+,[Trad],160.0,1,NaN,NaN,California,Rattlesnake Canyon,1,0,"['5.10-', '5.9+', '5.10a']",NaN,1.764951,2,4.0,3
5954,Connect Top Central Fins,0.5,2,5.3,[Trad],120.0,1,PG13,NaN,California,Rush,1,0,"['5.10c/d', '5.9+', '5.7', '5.10a', '5.2', '5....",NaN,1.098285,1,1.0,22
5955,Cause for Comotion,1.0,1,V1,[Boulder],10.0,1,NaN,NaN,Nevada,Library,1,0,"['V2', 'V3', 'V5']",NaN,1.647427,3,NaN,3
5956,Rabicano,2.0,1,V2,[Boulder],14.0,1,NaN,NaN,California,Jimmy Cliff Area,1,0,"['V-easy', 'V1', 'V-easy', 'V0-', 'V5']",NaN,2.147427,4,NaN,5
5957,Right Face Right Side,2.5,2,5.6,[TR],60.0,1,NaN,NaN,California,Silver Lake,0,0,"['5.8', '5.6', '5.3', '5.9', '5.10b', '5.9', '...",NaN,2.431618,1,3.0,11
5958,Problem A,1.0,1,V0+,[Boulder],12.0,1,NaN,NaN,California,Outback Bouldering,0,0,"['V0', 'V-easy']",NaN,1.647427,2,NaN,2
5960,Left Handed Drummer,3.0,1,5.11a,[Sport],70.0,1,NaN,NaN,California,Rock Creek,2,0,"['5.11b', '5.10-', '5.8', '5.10', '5.10c', '5....",NaN,2.647427,4,11.0,10
5961,His & Hers,1.0,1,5.9,[Trad],40.0,1,NaN,NaN,California,Rush,1,0,"['5.11a', '5.10d', '5.11c', '5.11b']",NaN,1.647427,2,6.0,4
5962,Number 5,3.0,4,5.12b,[Sport],40.0,1,NaN,NaN,Nevada,05-Sandstone Qu…,0,2,"['5.11d', '5.11d', '5.12b', '5.12a']",NaN,2.858971,6,16.0,4
5963,Alive Alone,2.0,2,5.10c/d,[Sport],70.0,1,NaN,NaN,California,Little Egypt,0,2,"['5.10c', '5.10a', '5.12b']",NaN,2.098285,3,9.0,3
5964,Family Flake,2.7,6,5.6,"[Trad, Alpine]",280.0,2,PG13,NaN,California,Cathedral Peak,3,0,"['5.7', '5.7', '5.5', '5.10a', '5.6', '5.7', '...",NaN,2.642122,1,3.0,13
5965,Beverly's Tower,2.7,133,5.10a,[Trad],100.0,1,NaN,NaN,California,h. Cookie Area,1,10,"['5.11b', '5.12b', '5.10b', '5.11c', '5.11a', ...",NaN,2.696977,2,7.0,34
5966,Ziggy,1.5,2,V3,[Boulder],12.0,1,NaN,NaN,California,Jimmy Cliff Area,2,0,"['V1', 'V-easy', 'V0', 'V0-', 'V0-', 'V-easy',...",NaN,1.764951,5,NaN,8
5967,Fun Monkey (aka Pride and Joy),2.6,8,5.7,[Sport],60.0,1,NaN,NaN,California,Sherwin Plateau,1,0,"['5.8', '5.9+', '5.8', '5.8+', '5.10-', '5.7',...",NaN,2.566095,2,4.0,25
5968,Killer Green Spud,2.1,19,5.10c,[Sport],30.0,1,NaN,NaN,California,Potato Patch,1,0,['5.8'],NaN,2.109743,3,9.0,1
5969,Mirkwood,2.0,3,5.10d,[Trad],450.0,5,PG13,III,Nevada,09-Icebox Canyon,6,0,['5.10+'],NaN,2.073713,3,10.0,1
5970,Consummate V's,1.0,1,V3,"[Boulder, Alpine]",8.0,1,NaN,NaN,California,Upper Meadow,1,0,"['V7', 'V4']",NaN,1.647427,5,NaN,2
5971,Morsel,1.6,8,V-easy,[Boulder],10.0,1,NaN,NaN,California,HVCG West,2,0,"['V-easy', 'V-easy', 'V-easy', 'V-easy', 'V1',...",NaN,1.677206,1,NaN,7
5972,The Cookie-Right,2.7,40,5.9,[Trad],170.0,3,NaN,NaN,California,h. Cookie Area,0,6,"['5.11b', '5.12b', '5.10b', '5.10a', '5.11c', ...",NaN,2.690118,2,6.0,34
5973,Wall Of Separation,1.3,3,5.9,[Sport],250.0,2,NaN,NaN,California,Little Egypt,0,2,"['5.10b', '5.10c', '5.11b', '5.11d', '5.10', '...",NaN,1.548713,2,6.0,7
5974,American Ninja,2.7,20,5.11a,[Trad],100.0,1,NaN,NaN,Nevada,10-Pine Creek C…,4,4,"['5.10+', '5.9', '5.10b', '5.10c', '5.9', '5.9...",NaN,2.680707,4,11.0,7
5976,Smears for Fears,3.7,12,5.11b/c,[Trad],100.0,1,NaN,NaN,Nevada,09-Icebox Canyon,2,2,"['5.10a', '5.9+', '5.7', '5.11d', '5.10a']",NaN,3.591912,4,12.0,5
5978,The World Is My Oyster,1.0,2,V1,[Boulder],15.0,1,NaN,NaN,California,Central - Maxim…,1,0,"['V5', 'V2', 'V2', 'V4', 'V1']",NaN,1.431618,3,NaN,5
5980,Last Out,2.2,20,5.10b,[Trad],60.0,1,NaN,NaN,Nevada,05-Sandstone Qu…,0,0,"['5.9-', '5.11d', '5.9', '5.8', '5.10a', '5.11...",NaN,2.204517,2,8.0,27
5981,Supersizer,4.0,1,5.12b,[Sport],115.0,1,NaN,NaN,California,Bear Crag,0,1,"['5.11d', '5.12a', '5.11c', '5.11c', '5.11b', ...",NaN,3.147427,6,16.0,9
5982,Deadwood Arete,1.0,1,V-easy,[Boulder],10.0,1,NaN,NaN,California,Real Hidden Val…,1,0,[],NaN,1.647427,1,NaN,0
5983,Dream Sequence,3.3,21,V6,[Boulder],13.0,1,NaN,NaN,California,Lonely Stones 1,3,4,"['V5', 'V-easy', 'V-easy', 'V1', 'V4']",NaN,3.254312,8,NaN,5
5984,Tomo Ari Gato (aka Lovin' Life),2.8,9,5.8,[Sport],60.0,1,NaN,NaN,California,Sherwin Plateau,1,1,"['5.9+', '5.8', '5.8+', '5.7', '5.10-', '5.7',...",NaN,2.749485,2,5.0,25

In [38]:
def diff_near_grades(row):
    """Finds the difference between the average grades of nearby routes
    and the average grade of the current route."""
    if int(row['number_near_grades']) == 0: #If there are no routes nearby
        return None
    else: 
        near_routes = row.near_grades
        near_routes = near_routes.split()
        sum_grades = 0
        for route in near_routes:
            sum_grades = sum_grades + combined_difficulty(route)
    average_nearby = sum_grades / len(near_routes)
    current_grade = combined_difficulty(row.grade)
    difference = abs(current_grade - average_nearby)
    return difference

    
diff_near_grades(df.iloc[100])

df['diff_nearby_grades'] = df.apply(lambda row: diff_near_grades(row), axis=1)
df.head()

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,sub_area,photos,comments,near_grades,aid_grade,popularity,combined_difficulty,difficulty_sport_trad,number_near_grades,diff_nearby_grades
0,Going Both Ways,3.5,17,5.11c,"[Sport, Alpine]",60.0,1,NaN,NaN,California,Dike Wall,1,0,"['5.11a', '5.11d', '5.11b', '5.11b', '5.10c', ...",NaN,3.433047,5,13.0,13,1.307692
1,Too Close for Comfort,2.0,2,5.11d,[Sport],40.0,1,NaN,NaN,California,Main Island,0,0,"['5.10a', '5.10a', '5.6', '5.8', '5.10b', '5.1...",NaN,2.098285,5,14.0,6,2.666667
2,Victim of AIDS,3.1,22,5.12a,"[Trad, TR, Aid]",25.0,1,NaN,NaN,California,Mt Woodson,1,5,"['5.8', '5.7', '5.8', '5.10a']",NaN,3.064994,6,15.0,4,4.000000
3,Christmas in July,2.4,8,5.10b/c,[Sport],100.0,1,NaN,NaN,California,Rock Creek,1,0,"['5.10', '5.10c', '5.10d', '5.11', '5.10b', '5...",NaN,2.388317,2,8.0,16,1.250000
4,Bridge of Sighs,2.8,4,5.11a,[Trad],50.0,1,R,NaN,California,Rattlesnake Canyon,0,1,[],NaN,2.698971,4,11.0,0,NaN

In [21]:
def find_safety_val(row):
    """Creates a new row where safety ratings correspond to numerical values."""
    safety_categorical = row['safety']
    if safety_categorical == 'PG13':
        safety_numerical = 1
    elif safety_categorical == 'R':
        safety_numerical = 2
    elif safety_categorical == 'X':
        safety_numerical = 3
    else:
        return None
    return safety_numerical

df['safety_numerical'] = df.apply(lambda row: find_safety_val(row), axis = 1)
df

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,...,photos,comments,near_grades,aid_grade,popularity,combined_difficulty,difficulty_sport_trad,number_near_grades,diff_nearby_grades,safety_numerical
0,The High Road,2.8,26,V7,[Boulder],25.0,1,NaN,NaN,Nevada,...,1,4,"['V3', 'V7', 'V1', 'V2', 'V9-', 'V7-', 'V5', '...",NaN,2.781291,9,NaN,12,2.500000,NaN
2,White Tigers,2.1,14,5.10b,[Sport],80.0,1,PG13,NaN,Nevada,...,1,1,"['5.10c', '5.9', '5.10a', '5.9']",NaN,2.112990,2,8.0,4,0.250000,1.0
3,Van Betten Arête,3.4,16,V3,[Boulder],10.0,1,NaN,NaN,Nevada,...,2,1,[],NaN,3.334991,5,NaN,0,NaN,NaN
4,Blue Steel Heat,3.0,1,V5,[Boulder],15.0,1,NaN,NaN,California,...,3,1,"['V0', 'V1', 'V1+', 'V4', 'V6', 'V1']",NaN,2.647427,7,NaN,6,2.833333,NaN
6,Paul's Penis,1.0,2,V0,[Boulder],18.0,1,NaN,NaN,California,...,1,0,[],NaN,1.431618,2,NaN,0,NaN,NaN
8,"Not So High, but High Enough",2.0,2,V0,[Boulder],18.0,1,PG13,NaN,California,...,1,0,"['V1', 'V0', 'V2+', 'V1+', 'V-easy', 'V2']",NaN,2.098285,2,NaN,6,0.833333,1.0
9,Dolphin Safe,2.5,31,5.7,"[Trad, Sport]",110.0,1,R,NaN,Nevada,...,1,4,"['5.8', '5.9', '5.3', '5.5', '5.6', '5.8', '5....",NaN,2.493589,2,4.0,12,0.333333,2.0
10,Problem F,0.5,2,V0-,[Boulder],10.0,1,NaN,NaN,California,...,0,0,"['V5+', 'V3', 'V0+', 'V2', 'V2', 'V3', 'V0+', ...",NaN,1.098285,2,NaN,8,2.125000,NaN
13,Through Bein' Cool,2.5,2,5.10c,[Trad],85.0,1,NaN,NaN,California,...,0,1,"['5.9', '5.12a', '5.12b']",NaN,2.431618,3,9.0,3,1.666667,NaN
14,The Itsy Bitsy Spider,3.0,1,5.10,[Trad],400.0,3,NaN,II,Nevada,...,2,0,"['5.8+', '5.7', '5.8', '5.8', '5.8', '5.5', '5...",NaN,2.647427,3,7.0,23,0.956522,NaN
15,Problem A,1.0,1,V0+,[Boulder],12.0,1,NaN,NaN,California,...,0,0,"['V0', 'V-easy']",NaN,1.647427,2,NaN,2,0.500000,NaN
16,The Thumb Aid Climb,2.5,4,5.10c,[Aid],35.0,1,NaN,NaN,California,...,1,2,"['5.12-', '5.6', '5.12a', '5.11c', '5.8', '5.9...",NaN,2.458971,3,9.0,55,0.000000,NaN
17,High Heeled Sneakers,3.0,3,V5,[Boulder],18.0,1,NaN,NaN,California,...,1,1,"['V3', 'V0', 'V-easy']",NaN,2.823713,7,NaN,3,4.333333,NaN
18,Left Wing Route - AKA The Democrat,1.7,3,5.6,[Sport],70.0,1,NaN,NaN,California,...,0,2,"['5.9', '5.8', '5.7', '5.10b', '5.10a', '5.8',...",NaN,1.848713,1,3.0,8,1.000000,NaN
19,Crab On A Slab,2.4,36,5.8,[Sport],50.0,1,NaN,V,Nevada,...,0,6,"['5.6', '5.7', '5.7', '5.5', '5.5', '5.7', '5....",NaN,2.397158,2,5.0,14,0.357143,NaN
21,The Wasp Roof,2.0,3,V6,[Boulder],6.0,1,NaN,NaN,California,...,1,2,[],NaN,2.073713,8,NaN,0,NaN,NaN
22,Roni Size,3.5,2,V4+,[Boulder],13.0,1,NaN,NaN,Nevada,...,1,0,['V2'],NaN,3.098285,6,NaN,1,2.000000,NaN
23,Dudes Squeezin Chicks,2.5,4,5.11b,[Sport],100.0,1,NaN,NaN,California,...,0,0,"['5.11d', '5.12b', '5.11a', '5.11d', '5.11b', ...",NaN,2.458971,4,12.0,11,1.272727,NaN
24,Watermark,3.5,2,V5+,[Boulder],12.0,1,NaN,NaN,Nevada,...,1,0,[],NaN,3.098285,7,NaN,0,NaN,NaN
25,Crooked Crack,1.0,1,5.8,[Trad],50.0,1,NaN,NaN,California,...,1,0,['5.9'],NaN,1.647427,2,5.0,1,0.000000,NaN
26,Sleezy Mormon,1.0,1,5.10d,"[Trad, Aid]",90.0,1,NaN,NaN,California,...,0,3,"['5.10', '5.9', '5.10b', '5.6', '5.10a', '5.9']",NaN,1.647427,3,10.0,6,1.000000,NaN
27,Center Slab Mid-Right,2.5,2,5.9,[TR],65.0,1,NaN,NaN,California,...,0,0,"['5.8', '5.8+', '5.9', '5.3', '5.8', '5.6']",NaN,2.431618,2,6.0,6,0.333333,NaN
28,Lynn Hill Memorial Face Problem,3.6,41,V4,[Boulder],20.0,1,NaN,NaN,California,...,4,8,"['V3', 'V-easy', 'V0', 'V2']",NaN,3.568925,6,NaN,4,3.000000,NaN
30,Pick Your Poison Center,1.4,17,5.9,[TR],100.0,1,NaN,NaN,California,...,0,0,"['5.6', '5.8', '5.10a', '5.5', '5.11b', '5.8',...",NaN,1.449714,2,6.0,7,0.142857,NaN
31,"Turtle Face, Left",2.7,54,V1,[Boulder],20.0,1,NaN,NaN,California,...,4,2,"['V4', 'V-easy', 'V-easy', 'V0', 'V0-', 'V2']",NaN,2.692634,3,NaN,6,0.333333,NaN
32,Streak on the Slab,2.4,38,5.10a,[Sport],50.0,1,NaN,NaN,Nevada,...,1,3,"['5.6', '5.7', '5.8', '5.7', '5.5', '5.5', '5....",NaN,2.397304,2,7.0,14,0.357143,NaN
33,Holey Gully,3.1,11,5.8+,[Trad],70.0,1,NaN,NaN,California,...,4,0,"['5.11d', '5.10c', '5.10a', '5.12a', '5.10a', ...",NaN,3.032904,2,5.0,18,1.111111,NaN
34,Skatement,1.0,1,V6,[Boulder],10.0,1,NaN,NaN,California,...,0,0,"['V0', 'V0-', 'V3', 'V4', 'V6']",NaN,1.647427,8,NaN,5,3.400000,NaN
35,Mainland Temple of the Perfect Wave,2.0,2,V1+,[Boulder],20.0,1,PG13,NaN,California,...,0,0,"['V4', 'V4', 'V0-', 'V-easy', 'V1', 'V1', 'V1'...",NaN,2.098285,3,NaN,9,0.555556,1.0
36,Sun is Shining,1.0,4,V-easy,[Boulder],11.0,1,NaN,NaN,California,...,1,0,"['V1', 'V0', 'V0-', 'V0-', 'V-easy', 'V-easy',...",NaN,1.258971,1,NaN,8,1.125000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5948,R2D2,2.4,5,5.8,[Trad],180.0,1,R,NaN,California,...,0,1,"['5.9', '5.10a', '5.11a', '5.7', '5.11-', '5.1...",NaN,2.382476,2,5.0,8,0.625000,2.0
5950,Galen's Crack,3.2,43,5.10c,"[Trad, TR]",45.0,1,NaN,NaN,California,...,3,8,[],NaN,3.179428,3,9.0,0,NaN,NaN
5951,Ledge Problem,2.0,1,V0+,[Boulder],15.0,1,NaN,NaN,California,...,1,0,"['V0', 'V3', 'V5', 'V6']",NaN,2.147427,2,NaN,4,3.500000,NaN
5952,Bury Me With My Boots On,1.5,2,5.10-,[Trad],300.0,3,R,NaN,California,...,1,0,"['5.9+', '5.10a', '5.7+']",NaN,1.764951,2,7.0,3,0.000000,2.0
5953,Lord of the Apes,2.0,1,5.12a,"[Trad, TR]",40.0,1,NaN,NaN,California,...,1,0,[],NaN,2.147427,6,15.0,0,NaN,NaN
5954,Lessons In Flight,2.0,1,V2,[Boulder],20.0,1,NaN,NaN,California,...,2,0,[],NaN,2.147427,4,NaN,0,NaN,NaN
5955,Generation Direct,3.7,3,V7,[Boulder],30.0,1,PG13,NaN,California,...,1,0,[],NaN,3.348713,9,NaN,0,NaN,1.0
5957,Udder Chaos,2.3,4,5.8,"[Trad, Sport]",160.0,1,PG13,NaN,California,...,1,0,"['5.5', 'Easy 5th', '5.7', '5.6', '5.8']",NaN,2.298971,2,5.0,6,0.666667,1.0
5958,Cotton Headed Ninny Muggins,3.0,1,5.10b,[Trad],160.0,1,NaN,NaN,California,...,2,0,"['5.10a/b', '5.10d', '5.11a/b', '5.8', '5.9', ...",NaN,2.647427,2,8.0,8,0.875000,NaN
5959,Michael Caine Sit Start,2.0,1,V12,[Boulder],15.0,1,NaN,NaN,California,...,0,1,"['V0', 'V0', 'V11', 'V8', 'V7', 'V4', 'V9-', '...",NaN,2.147427,14,NaN,15,6.066667,NaN
5960,Puff Aider,3.0,2,5.10,"[Trad, Aid]",250.0,2,NaN,II,California,...,3,0,"['5.8', '5.11', '5.8', '5.11', '5.9', '5.9', '...",A2,2.764951,3,7.0,12,0.250000,NaN
5961,Cowboy Marmot,3.1,32,5.8,[Trad],500.0,5,NaN,NaN,California,...,7,18,['5.9'],NaN,3.075602,2,5.0,1,0.000000,NaN
5964,Tatanka,3.0,2,5.10,"[Trad, Aid]",900.0,8,R,IV,Nevada,...,6,2,['5.12c'],A2-3,2.764951,3,7.0,1,4.000000,2.0
5965,Rotator Cuff,3.0,1,V3-4,[Boulder],20.0,1,NaN,NaN,Nevada,...,1,0,[],NaN,2.647427,5,NaN,0,NaN,NaN
5968,Squirty,1.0,1,5.8,[Trad],40.0,1,NaN,NaN,California,...,0,0,"['5.9', '5.7', '5.7+', '5.9', '5.9', '5.10a/b'...",NaN,1.647427,2,5.0,13,0.000000,NaN
5969,False Grit,1.0,1,V3,[Boulder],13.0,1,NaN,NaN,California,...,0,0,"['V1', 'V2', 'V-easy', 'V5', 'V3', 'V0-1', 'V0...",NaN,1.647427,5,NaN,9,1.222222,NaN
5970,Triple Delight,3.0,41,5.10a/b,[Sport],100.0,1,NaN,NaN,California,...,1,5,"['5.10c', '5.8', '5.10a', '5.10b', '5.9', '5.9...",NaN,2.983211,2,7.0,18,0.111111,NaN
5971,Blood Mantel,1.0,3,V4,[Boulder],15.0,1,NaN,NaN,California,...,1,0,"['V-easy', 'V-easy', 'V0', 'V0-', 'V2', 'V1']",NaN,1.323713,6,NaN,6,3.833333,NaN
5972,Panty Line,2.8,76,5.10a,"[Trad, TR]",80.0,1,R,NaN,Nevada,...,1,6,"['5.8', '5.8', '5.8', '5.11-', '5.10d', '5.5',...",NaN,2.793440,2,7.0,26,0.653846,2.0
5973,Squirt,1.6,13,V0,[Boulder],12.0,1,NaN,NaN,California,...,1,1,"['V-easy', 'V4', 'V-easy']",NaN,1.649632,2,NaN,3,0.666667,NaN
5974,Battered Men Shelter,0.5,2,V0,[Boulder],15.0,1,NaN,NaN,California,...,2,0,"['V5', 'V1', 'V1+', 'V4', 'V6', 'V1']",NaN,1.098285,2,NaN,6,3.000000,NaN
5975,Gobs of Knobs,1.0,1,5.11,[TR],200.0,1,NaN,NaN,California,...,0,0,"['5.10', '5.10c', '5.10b/c', '5.10d', '5.10b',...",NaN,1.647427,5,11.0,16,1.937500,NaN
5976,The Blade,1.0,1,5.12-,"[Trad, TR]",30.0,1,NaN,NaN,California,...,0,0,"['5.10d', '5.11c', '5.10c']",NaN,1.647427,6,15.0,3,2.333333,NaN
5977,Another Unnamed V3,3.0,1,V3,[Boulder],10.0,1,NaN,NaN,California,...,1,0,[],NaN,2.647427,5,NaN,0,NaN,NaN
5978,Warm-Down,1.0,4,V-easy,[Boulder],10.0,1,R,NaN,California,...,0,0,"['V0', 'V4', 'V6', 'V3', 'V5', 'V-easy']",NaN,1.258971,1,NaN,6,3.833333,2.0
5979,Pocket Wall,2.7,6,V0,[Boulder],12.0,1,NaN,NaN,California,...,1,0,"['V0', 'V3', 'V0', 'V4', 'V0', 'V1', 'V0', 'V0...",NaN,2.642122,2,NaN,10,1.000000,NaN
5980,Sharp shells,2.0,1,V3,[Boulder],12.0,1,NaN,NaN,Nevada,...,1,0,['V4-'],NaN,2.147427,5,NaN,1,1.000000,NaN
5981,Ultraman,3.0,103,5.8+,[Sport],130.0,1,R,NaN,Nevada,...,9,15,"['5.9', '5.10-', '5.7', '5.6', '5.9', '5.7+', ...",NaN,2.993220,2,5.0,13,0.153846,2.0
5982,F-22 Raptor,1.0,1,5.7,[Trad],65.0,1,NaN,NaN,Nevada,...,0,0,"['5.10c/d', '5.8+', '5.10a', '5.9', '5.7', '5....",NaN,1.647427,2,4.0,24,0.000000,NaN
5983,Handbone,3.2,59,5.10,[Trad],70.0,1,NaN,NaN,Nevada,...,7,10,"['5.11', '5.10a', '5.10+', '5.12a', '5.11a', '...",NaN,3.184914,3,7.0,15,1.466667,NaN

In [22]:
def find_commitment_val(row):
    """Creates a new row where commitment ratings correspond to a numerical value."""
    commitment_categorical = row['commitment']
    if commitment_categorical == 'I':
        commitment_numerical = 1
    elif commitment_categorical == 'II':
        commitment_numerical = 2
    elif commitment_categorical == 'III':
        commitment_numerical = 3
    elif commitment_categorical == 'IV':
        commitment_numerical = 4
    elif commitment_categorical == 'V':
        commitment_numerical = 5
    elif commitment_categorical == 'VI':
        commitment_numerical = 6
    elif commitment_categorical == 'VII':
        commitment_numerical = 7
    else:
        return 1
    return commitment_numerical

df['commitment_numerical'] = df.apply(lambda row: find_commitment_val(row), axis = 1)
df

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,...,comments,near_grades,aid_grade,popularity,combined_difficulty,difficulty_sport_trad,number_near_grades,diff_nearby_grades,safety_numerical,commitment_numerical
0,The High Road,2.8,26,V7,[Boulder],25.0,1,NaN,NaN,Nevada,...,4,"['V3', 'V7', 'V1', 'V2', 'V9-', 'V7-', 'V5', '...",NaN,2.781291,9,NaN,12,2.500000,NaN,1
2,White Tigers,2.1,14,5.10b,[Sport],80.0,1,PG13,NaN,Nevada,...,1,"['5.10c', '5.9', '5.10a', '5.9']",NaN,2.112990,2,8.0,4,0.250000,1.0,1
3,Van Betten Arête,3.4,16,V3,[Boulder],10.0,1,NaN,NaN,Nevada,...,1,[],NaN,3.334991,5,NaN,0,NaN,NaN,1
4,Blue Steel Heat,3.0,1,V5,[Boulder],15.0,1,NaN,NaN,California,...,1,"['V0', 'V1', 'V1+', 'V4', 'V6', 'V1']",NaN,2.647427,7,NaN,6,2.833333,NaN,1
6,Paul's Penis,1.0,2,V0,[Boulder],18.0,1,NaN,NaN,California,...,0,[],NaN,1.431618,2,NaN,0,NaN,NaN,1
8,"Not So High, but High Enough",2.0,2,V0,[Boulder],18.0,1,PG13,NaN,California,...,0,"['V1', 'V0', 'V2+', 'V1+', 'V-easy', 'V2']",NaN,2.098285,2,NaN,6,0.833333,1.0,1
9,Dolphin Safe,2.5,31,5.7,"[Trad, Sport]",110.0,1,R,NaN,Nevada,...,4,"['5.8', '5.9', '5.3', '5.5', '5.6', '5.8', '5....",NaN,2.493589,2,4.0,12,0.333333,2.0,1
10,Problem F,0.5,2,V0-,[Boulder],10.0,1,NaN,NaN,California,...,0,"['V5+', 'V3', 'V0+', 'V2', 'V2', 'V3', 'V0+', ...",NaN,1.098285,2,NaN,8,2.125000,NaN,1
13,Through Bein' Cool,2.5,2,5.10c,[Trad],85.0,1,NaN,NaN,California,...,1,"['5.9', '5.12a', '5.12b']",NaN,2.431618,3,9.0,3,1.666667,NaN,1
14,The Itsy Bitsy Spider,3.0,1,5.10,[Trad],400.0,3,NaN,II,Nevada,...,0,"['5.8+', '5.7', '5.8', '5.8', '5.8', '5.5', '5...",NaN,2.647427,3,7.0,23,0.956522,NaN,2
15,Problem A,1.0,1,V0+,[Boulder],12.0,1,NaN,NaN,California,...,0,"['V0', 'V-easy']",NaN,1.647427,2,NaN,2,0.500000,NaN,1
16,The Thumb Aid Climb,2.5,4,5.10c,[Aid],35.0,1,NaN,NaN,California,...,2,"['5.12-', '5.6', '5.12a', '5.11c', '5.8', '5.9...",NaN,2.458971,3,9.0,55,0.000000,NaN,1
17,High Heeled Sneakers,3.0,3,V5,[Boulder],18.0,1,NaN,NaN,California,...,1,"['V3', 'V0', 'V-easy']",NaN,2.823713,7,NaN,3,4.333333,NaN,1
18,Left Wing Route - AKA The Democrat,1.7,3,5.6,[Sport],70.0,1,NaN,NaN,California,...,2,"['5.9', '5.8', '5.7', '5.10b', '5.10a', '5.8',...",NaN,1.848713,1,3.0,8,1.000000,NaN,1
19,Crab On A Slab,2.4,36,5.8,[Sport],50.0,1,NaN,V,Nevada,...,6,"['5.6', '5.7', '5.7', '5.5', '5.5', '5.7', '5....",NaN,2.397158,2,5.0,14,0.357143,NaN,5
21,The Wasp Roof,2.0,3,V6,[Boulder],6.0,1,NaN,NaN,California,...,2,[],NaN,2.073713,8,NaN,0,NaN,NaN,1
22,Roni Size,3.5,2,V4+,[Boulder],13.0,1,NaN,NaN,Nevada,...,0,['V2'],NaN,3.098285,6,NaN,1,2.000000,NaN,1
23,Dudes Squeezin Chicks,2.5,4,5.11b,[Sport],100.0,1,NaN,NaN,California,...,0,"['5.11d', '5.12b', '5.11a', '5.11d', '5.11b', ...",NaN,2.458971,4,12.0,11,1.272727,NaN,1
24,Watermark,3.5,2,V5+,[Boulder],12.0,1,NaN,NaN,Nevada,...,0,[],NaN,3.098285,7,NaN,0,NaN,NaN,1
25,Crooked Crack,1.0,1,5.8,[Trad],50.0,1,NaN,NaN,California,...,0,['5.9'],NaN,1.647427,2,5.0,1,0.000000,NaN,1
26,Sleezy Mormon,1.0,1,5.10d,"[Trad, Aid]",90.0,1,NaN,NaN,California,...,3,"['5.10', '5.9', '5.10b', '5.6', '5.10a', '5.9']",NaN,1.647427,3,10.0,6,1.000000,NaN,1
27,Center Slab Mid-Right,2.5,2,5.9,[TR],65.0,1,NaN,NaN,California,...,0,"['5.8', '5.8+', '5.9', '5.3', '5.8', '5.6']",NaN,2.431618,2,6.0,6,0.333333,NaN,1
28,Lynn Hill Memorial Face Problem,3.6,41,V4,[Boulder],20.0,1,NaN,NaN,California,...,8,"['V3', 'V-easy', 'V0', 'V2']",NaN,3.568925,6,NaN,4,3.000000,NaN,1
30,Pick Your Poison Center,1.4,17,5.9,[TR],100.0,1,NaN,NaN,California,...,0,"['5.6', '5.8', '5.10a', '5.5', '5.11b', '5.8',...",NaN,1.449714,2,6.0,7,0.142857,NaN,1
31,"Turtle Face, Left",2.7,54,V1,[Boulder],20.0,1,NaN,NaN,California,...,2,"['V4', 'V-easy', 'V-easy', 'V0', 'V0-', 'V2']",NaN,2.692634,3,NaN,6,0.333333,NaN,1
32,Streak on the Slab,2.4,38,5.10a,[Sport],50.0,1,NaN,NaN,Nevada,...,3,"['5.6', '5.7', '5.8', '5.7', '5.5', '5.5', '5....",NaN,2.397304,2,7.0,14,0.357143,NaN,1
33,Holey Gully,3.1,11,5.8+,[Trad],70.0,1,NaN,NaN,California,...,0,"['5.11d', '5.10c', '5.10a', '5.12a', '5.10a', ...",NaN,3.032904,2,5.0,18,1.111111,NaN,1
34,Skatement,1.0,1,V6,[Boulder],10.0,1,NaN,NaN,California,...,0,"['V0', 'V0-', 'V3', 'V4', 'V6']",NaN,1.647427,8,NaN,5,3.400000,NaN,1
35,Mainland Temple of the Perfect Wave,2.0,2,V1+,[Boulder],20.0,1,PG13,NaN,California,...,0,"['V4', 'V4', 'V0-', 'V-easy', 'V1', 'V1', 'V1'...",NaN,2.098285,3,NaN,9,0.555556,1.0,1
36,Sun is Shining,1.0,4,V-easy,[Boulder],11.0,1,NaN,NaN,California,...,0,"['V1', 'V0', 'V0-', 'V0-', 'V-easy', 'V-easy',...",NaN,1.258971,1,NaN,8,1.125000,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5948,R2D2,2.4,5,5.8,[Trad],180.0,1,R,NaN,California,...,1,"['5.9', '5.10a', '5.11a', '5.7', '5.11-', '5.1...",NaN,2.382476,2,5.0,8,0.625000,2.0,1
5950,Galen's Crack,3.2,43,5.10c,"[Trad, TR]",45.0,1,NaN,NaN,California,...,8,[],NaN,3.179428,3,9.0,0,NaN,NaN,1
5951,Ledge Problem,2.0,1,V0+,[Boulder],15.0,1,NaN,NaN,California,...,0,"['V0', 'V3', 'V5', 'V6']",NaN,2.147427,2,NaN,4,3.500000,NaN,1
5952,Bury Me With My Boots On,1.5,2,5.10-,[Trad],300.0,3,R,NaN,California,...,0,"['5.9+', '5.10a', '5.7+']",NaN,1.764951,2,7.0,3,0.000000,2.0,1
5953,Lord of the Apes,2.0,1,5.12a,"[Trad, TR]",40.0,1,NaN,NaN,California,...,0,[],NaN,2.147427,6,15.0,0,NaN,NaN,1
5954,Lessons In Flight,2.0,1,V2,[Boulder],20.0,1,NaN,NaN,California,...,0,[],NaN,2.147427,4,NaN,0,NaN,NaN,1
5955,Generation Direct,3.7,3,V7,[Boulder],30.0,1,PG13,NaN,California,...,0,[],NaN,3.348713,9,NaN,0,NaN,1.0,1
5957,Udder Chaos,2.3,4,5.8,"[Trad, Sport]",160.0,1,PG13,NaN,California,...,0,"['5.5', 'Easy 5th', '5.7', '5.6', '5.8']",NaN,2.298971,2,5.0,6,0.666667,1.0,1
5958,Cotton Headed Ninny Muggins,3.0,1,5.10b,[Trad],160.0,1,NaN,NaN,California,...,0,"['5.10a/b', '5.10d', '5.11a/b', '5.8', '5.9', ...",NaN,2.647427,2,8.0,8,0.875000,NaN,1
5959,Michael Caine Sit Start,2.0,1,V12,[Boulder],15.0,1,NaN,NaN,California,...,1,"['V0', 'V0', 'V11', 'V8', 'V7', 'V4', 'V9-', '...",NaN,2.147427,14,NaN,15,6.066667,NaN,1
5960,Puff Aider,3.0,2,5.10,"[Trad, Aid]",250.0,2,NaN,II,California,...,0,"['5.8', '5.11', '5.8', '5.11', '5.9', '5.9', '...",A2,2.764951,3,7.0,12,0.250000,NaN,2
5961,Cowboy Marmot,3.1,32,5.8,[Trad],500.0,5,NaN,NaN,California,...,18,['5.9'],NaN,3.075602,2,5.0,1,0.000000,NaN,1
5964,Tatanka,3.0,2,5.10,"[Trad, Aid]",900.0,8,R,IV,Nevada,...,2,['5.12c'],A2-3,2.764951,3,7.0,1,4.000000,2.0,4
5965,Rotator Cuff,3.0,1,V3-4,[Boulder],20.0,1,NaN,NaN,Nevada,...,0,[],NaN,2.647427,5,NaN,0,NaN,NaN,1
5968,Squirty,1.0,1,5.8,[Trad],40.0,1,NaN,NaN,California,...,0,"['5.9', '5.7', '5.7+', '5.9', '5.9', '5.10a/b'...",NaN,1.647427,2,5.0,13,0.000000,NaN,1
5969,False Grit,1.0,1,V3,[Boulder],13.0,1,NaN,NaN,California,...,0,"['V1', 'V2', 'V-easy', 'V5', 'V3', 'V0-1', 'V0...",NaN,1.647427,5,NaN,9,1.222222,NaN,1
5970,Triple Delight,3.0,41,5.10a/b,[Sport],100.0,1,NaN,NaN,California,...,5,"['5.10c', '5.8', '5.10a', '5.10b', '5.9', '5.9...",NaN,2.983211,2,7.0,18,0.111111,NaN,1
5971,Blood Mantel,1.0,3,V4,[Boulder],15.0,1,NaN,NaN,California,...,0,"['V-easy', 'V-easy', 'V0', 'V0-', 'V2', 'V1']",NaN,1.323713,6,NaN,6,3.833333,NaN,1
5972,Panty Line,2.8,76,5.10a,"[Trad, TR]",80.0,1,R,NaN,Nevada,...,6,"['5.8', '5.8', '5.8', '5.11-', '5.10d', '5.5',...",NaN,2.793440,2,7.0,26,0.653846,2.0,1
5973,Squirt,1.6,13,V0,[Boulder],12.0,1,NaN,NaN,California,...,1,"['V-easy', 'V4', 'V-easy']",NaN,1.649632,2,NaN,3,0.666667,NaN,1
5974,Battered Men Shelter,0.5,2,V0,[Boulder],15.0,1,NaN,NaN,California,...,0,"['V5', 'V1', 'V1+', 'V4', 'V6', 'V1']",NaN,1.098285,2,NaN,6,3.000000,NaN,1
5975,Gobs of Knobs,1.0,1,5.11,[TR],200.0,1,NaN,NaN,California,...,0,"['5.10', '5.10c', '5.10b/c', '5.10d', '5.10b',...",NaN,1.647427,5,11.0,16,1.937500,NaN,1
5976,The Blade,1.0,1,5.12-,"[Trad, TR]",30.0,1,NaN,NaN,California,...,0,"['5.10d', '5.11c', '5.10c']",NaN,1.647427,6,15.0,3,2.333333,NaN,1
5977,Another Unnamed V3,3.0,1,V3,[Boulder],10.0,1,NaN,NaN,California,...,0,[],NaN,2.647427,5,NaN,0,NaN,NaN,1
5978,Warm-Down,1.0,4,V-easy,[Boulder],10.0,1,R,NaN,California,...,0,"['V0', 'V4', 'V6', 'V3', 'V5', 'V-easy']",NaN,1.258971,1,NaN,6,3.833333,2.0,1
5979,Pocket Wall,2.7,6,V0,[Boulder],12.0,1,NaN,NaN,California,...,0,"['V0', 'V3', 'V0', 'V4', 'V0', 'V1', 'V0', 'V0...",NaN,2.642122,2,NaN,10,1.000000,NaN,1
5980,Sharp shells,2.0,1,V3,[Boulder],12.0,1,NaN,NaN,Nevada,...,0,['V4-'],NaN,2.147427,5,NaN,1,1.000000,NaN,1
5981,Ultraman,3.0,103,5.8+,[Sport],130.0,1,R,NaN,Nevada,...,15,"['5.9', '5.10-', '5.7', '5.6', '5.9', '5.7+', ...",NaN,2.993220,2,5.0,13,0.153846,2.0,1
5982,F-22 Raptor,1.0,1,5.7,[Trad],65.0,1,NaN,NaN,Nevada,...,0,"['5.10c/d', '5.8+', '5.10a', '5.9', '5.7', '5....",NaN,1.647427,2,4.0,24,0.000000,NaN,1
5983,Handbone,3.2,59,5.10,[Trad],70.0,1,NaN,NaN,Nevada,...,10,"['5.11', '5.10a', '5.10+', '5.12a', '5.11a', '...",NaN,3.184914,3,7.0,15,1.466667,NaN,1

In [23]:
def find_aid_val(row):
    if (type(row['aid_grade'])) == float:
        return None
    aid_categorical = str(row['aid_grade'])
    if(re.search('A0', aid_categorical)):
        aid_numerical = 1
    elif(re.search('A1', aid_categorical)):
        aid_numerical = 1    
    elif(re.search('A2', aid_categorical)):
        aid_numerical = 2
    elif(re.search('A3', aid_categorical)):
        aid_numerical = 3
    elif(re.search('A4', aid_categorical)):
        aid_numerical = 4
    elif(re.search('A5', aid_categorical)):
        aid_numerical = 5
    else:
        return None
    return aid_numerical

df['aid_numerical'] = df.apply(lambda row: find_aid_val(row), axis = 1)
df

,name,rating,votes,grade,type,height,pitches,safety,commitment,state,...,near_grades,aid_grade,popularity,combined_difficulty,difficulty_sport_trad,number_near_grades,diff_nearby_grades,safety_numerical,commitment_numerical,aid_numerical
0,The High Road,2.8,26,V7,[Boulder],25.0,1,NaN,NaN,Nevada,...,"['V3', 'V7', 'V1', 'V2', 'V9-', 'V7-', 'V5', '...",NaN,2.781291,9,NaN,12,2.500000,NaN,1,NaN
2,White Tigers,2.1,14,5.10b,[Sport],80.0,1,PG13,NaN,Nevada,...,"['5.10c', '5.9', '5.10a', '5.9']",NaN,2.112990,2,8.0,4,0.250000,1.0,1,NaN
3,Van Betten Arête,3.4,16,V3,[Boulder],10.0,1,NaN,NaN,Nevada,...,[],NaN,3.334991,5,NaN,0,NaN,NaN,1,NaN
4,Blue Steel Heat,3.0,1,V5,[Boulder],15.0,1,NaN,NaN,California,...,"['V0', 'V1', 'V1+', 'V4', 'V6', 'V1']",NaN,2.647427,7,NaN,6,2.833333,NaN,1,NaN
6,Paul's Penis,1.0,2,V0,[Boulder],18.0,1,NaN,NaN,California,...,[],NaN,1.431618,2,NaN,0,NaN,NaN,1,NaN
8,"Not So High, but High Enough",2.0,2,V0,[Boulder],18.0,1,PG13,NaN,California,...,"['V1', 'V0', 'V2+', 'V1+', 'V-easy', 'V2']",NaN,2.098285,2,NaN,6,0.833333,1.0,1,NaN
9,Dolphin Safe,2.5,31,5.7,"[Trad, Sport]",110.0,1,R,NaN,Nevada,...,"['5.8', '5.9', '5.3', '5.5', '5.6', '5.8', '5....",NaN,2.493589,2,4.0,12,0.333333,2.0,1,NaN
10,Problem F,0.5,2,V0-,[Boulder],10.0,1,NaN,NaN,California,...,"['V5+', 'V3', 'V0+', 'V2', 'V2', 'V3', 'V0+', ...",NaN,1.098285,2,NaN,8,2.125000,NaN,1,NaN
13,Through Bein' Cool,2.5,2,5.10c,[Trad],85.0,1,NaN,NaN,California,...,"['5.9', '5.12a', '5.12b']",NaN,2.431618,3,9.0,3,1.666667,NaN,1,NaN
14,The Itsy Bitsy Spider,3.0,1,5.10,[Trad],400.0,3,NaN,II,Nevada,...,"['5.8+', '5.7', '5.8', '5.8', '5.8', '5.5', '5...",NaN,2.647427,3,7.0,23,0.956522,NaN,2,NaN
15,Problem A,1.0,1,V0+,[Boulder],12.0,1,NaN,NaN,California,...,"['V0', 'V-easy']",NaN,1.647427,2,NaN,2,0.500000,NaN,1,NaN
16,The Thumb Aid Climb,2.5,4,5.10c,[Aid],35.0,1,NaN,NaN,California,...,"['5.12-', '5.6', '5.12a', '5.11c', '5.8', '5.9...",NaN,2.458971,3,9.0,55,0.000000,NaN,1,NaN
17,High Heeled Sneakers,3.0,3,V5,[Boulder],18.0,1,NaN,NaN,California,...,"['V3', 'V0', 'V-easy']",NaN,2.823713,7,NaN,3,4.333333,NaN,1,NaN
18,Left Wing Route - AKA The Democrat,1.7,3,5.6,[Sport],70.0,1,NaN,NaN,California,...,"['5.9', '5.8', '5.7', '5.10b', '5.10a', '5.8',...",NaN,1.848713,1,3.0,8,1.000000,NaN,1,NaN
19,Crab On A Slab,2.4,36,5.8,[Sport],50.0,1,NaN,V,Nevada,...,"['5.6', '5.7', '5.7', '5.5', '5.5', '5.7', '5....",NaN,2.397158,2,5.0,14,0.357143,NaN,5,NaN
21,The Wasp Roof,2.0,3,V6,[Boulder],6.0,1,NaN,NaN,California,...,[],NaN,2.073713,8,NaN,0,NaN,NaN,1,NaN
22,Roni Size,3.5,2,V4+,[Boulder],13.0,1,NaN,NaN,Nevada,...,['V2'],NaN,3.098285,6,NaN,1,2.000000,NaN,1,NaN
23,Dudes Squeezin Chicks,2.5,4,5.11b,[Sport],100.0,1,NaN,NaN,California,...,"['5.11d', '5.12b', '5.11a', '5.11d', '5.11b', ...",NaN,2.458971,4,12.0,11,1.272727,NaN,1,NaN
24,Watermark,3.5,2,V5+,[Boulder],12.0,1,NaN,NaN,Nevada,...,[],NaN,3.098285,7,NaN,0,NaN,NaN,1,NaN
25,Crooked Crack,1.0,1,5.8,[Trad],50.0,1,NaN,NaN,California,...,['5.9'],NaN,1.647427,2,5.0,1,0.000000,NaN,1,NaN
26,Sleezy Mormon,1.0,1,5.10d,"[Trad, Aid]",90.0,1,NaN,NaN,California,...,"['5.10', '5.9', '5.10b', '5.6', '5.10a', '5.9']",NaN,1.647427,3,10.0,6,1.000000,NaN,1,NaN
27,Center Slab Mid-Right,2.5,2,5.9,[TR],65.0,1,NaN,NaN,California,...,"['5.8', '5.8+', '5.9', '5.3', '5.8', '5.6']",NaN,2.431618,2,6.0,6,0.333333,NaN,1,NaN
28,Lynn Hill Memorial Face Problem,3.6,41,V4,[Boulder],20.0,1,NaN,NaN,California,...,"['V3', 'V-easy', 'V0', 'V2']",NaN,3.568925,6,NaN,4,3.000000,NaN,1,NaN
30,Pick Your Poison Center,1.4,17,5.9,[TR],100.0,1,NaN,NaN,California,...,"['5.6', '5.8', '5.10a', '5.5', '5.11b', '5.8',...",NaN,1.449714,2,6.0,7,0.142857,NaN,1,NaN
31,"Turtle Face, Left",2.7,54,V1,[Boulder],20.0,1,NaN,NaN,California,...,"['V4', 'V-easy', 'V-easy', 'V0', 'V0-', 'V2']",NaN,2.692634,3,NaN,6,0.333333,NaN,1,NaN
32,Streak on the Slab,2.4,38,5.10a,[Sport],50.0,1,NaN,NaN,Nevada,...,"['5.6', '5.7', '5.8', '5.7', '5.5', '5.5', '5....",NaN,2.397304,2,7.0,14,0.357143,NaN,1,NaN
33,Holey Gully,3.1,11,5.8+,[Trad],70.0,1,NaN,NaN,California,...,"['5.11d', '5.10c', '5.10a', '5.12a', '5.10a', ...",NaN,3.032904,2,5.0,18,1.111111,NaN,1,NaN
34,Skatement,1.0,1,V6,[Boulder],10.0,1,NaN,NaN,California,...,"['V0', 'V0-', 'V3', 'V4', 'V6']",NaN,1.647427,8,NaN,5,3.400000,NaN,1,NaN
35,Mainland Temple of the Perfect Wave,2.0,2,V1+,[Boulder],20.0,1,PG13,NaN,California,...,"['V4', 'V4', 'V0-', 'V-easy', 'V1', 'V1', 'V1'...",NaN,2.098285,3,NaN,9,0.555556,1.0,1,NaN
36,Sun is Shining,1.0,4,V-easy,[Boulder],11.0,1,NaN,NaN,California,...,"['V1', 'V0', 'V0-', 'V0-', 'V-easy', 'V-easy',...",NaN,1.258971,1,NaN,8,1.125000,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5948,R2D2,2.4,5,5.8,[Trad],180.0,1,R,NaN,California,...,"['5.9', '5.10a', '5.11a', '5.7', '5.11-', '5.1...",NaN,2.382476,2,5.0,8,0.625000,2.0,1,NaN
5950,Galen's Crack,3.2,43,5.10c,"[Trad, TR]",45.0,1,NaN,NaN,California,...,[],NaN,3.179428,3,9.0,0,NaN,NaN,1,NaN
5951,Ledge Problem,2.0,1,V0+,[Boulder],15.0,1,NaN,NaN,California,...,"['V0', 'V3', 'V5', 'V6']",NaN,2.147427,2,NaN,4,3.500000,NaN,1,NaN
5952,Bury Me With My Boots On,1.5,2,5.10-,[Trad],300.0,3,R,NaN,California,...,"['5.9+', '5.10a', '5.7+']",NaN,1.764951,2,7.0,3,0.000000,2.0,1,NaN
5953,Lord of the Apes,2.0,1,5.12a,"[Trad, TR]",40.0,1,NaN,NaN,California,...,[],NaN,2.147427,6,15.0,0,NaN,NaN,1,NaN
5954,Lessons In Flight,2.0,1,V2,[Boulder],20.0,1,NaN,NaN,California,...,[],NaN,2.147427,4,NaN,0,NaN,NaN,1,NaN
5955,Generation Direct,3.7,3,V7,[Boulder],30.0,1,PG13,NaN,California,...,[],NaN,3.348713,9,NaN,0,NaN,1.0,1,NaN
5957,Udder Chaos,2.3,4,5.8,"[Trad, Sport]",160.0,1,PG13,NaN,California,...,"['5.5', 'Easy 5th', '5.7', '5.6', '5.8']",NaN,2.298971,2,5.0,6,0.666667,1.0,1,NaN
5958,Cotton Headed Ninny Muggins,3.0,1,5.10b,[Trad],160.0,1,NaN,NaN,California,...,"['5.10a/b', '5.10d', '5.11a/b', '5.8', '5.9', ...",NaN,2.647427,2,8.0,8,0.875000,NaN,1,NaN
5959,Michael Caine Sit Start,2.0,1,V12,[Boulder],15.0,1,NaN,NaN,California,...,"['V0', 'V0', 'V11', 'V8', 'V7', 'V4', 'V9-', '...",NaN,2.147427,14,NaN,15,6.066667,NaN,1,NaN
5960,Puff Aider,3.0,2,5.10,"[Trad, Aid]",250.0,2,NaN,II,California,...,"['5.8', '5.11', '5.8', '5.11', '5.9', '5.9', '...",A2,2.764951,3,7.0,12,0.250000,NaN,2,2.0
5961,Cowboy Marmot,3.1,32,5.8,[Trad],500.0,5,NaN,NaN,California,...,['5.9'],NaN,3.075602,2,5.0,1,0.000000,NaN,1,NaN
5964,Tatanka,3.0,2,5.10,"[Trad, Aid]",900.0,8,R,IV,Nevada,...,['5.12c'],A2-3,2.764951,3,7.0,1,4.000000,2.0,4,2.0
5965,Rotator Cuff,3.0,1,V3-4,[Boulder],20.0,1,NaN,NaN,Nevada,...,[],NaN,2.647427,5,NaN,0,NaN,NaN,1,NaN
5968,Squirty,1.0,1,5.8,[Trad],40.0,1,NaN,NaN,California,...,"['5.9', '5.7', '5.7+', '5.9', '5.9', '5.10a/b'...",NaN,1.647427,2,5.0,13,0.000000,NaN,1,NaN
5969,False Grit,1.0,1,V3,[Boulder],13.0,1,NaN,NaN,California,...,"['V1', 'V2', 'V-easy', 'V5', 'V3', 'V0-1', 'V0...",NaN,1.647427,5,NaN,9,1.222222,NaN,1,NaN
5970,Triple Delight,3.0,41,5.10a/b,[Sport],100.0,1,NaN,NaN,California,...,"['5.10c', '5.8', '5.10a', '5.10b', '5.9', '5.9...",NaN,2.983211,2,7.0,18,0.111111,NaN,1,NaN
5971,Blood Mantel,1.0,3,V4,[Boulder],15.0,1,NaN,NaN,California,...,"['V-easy', 'V-easy', 'V0', 'V0-', 'V2', 'V1']",NaN,1.323713,6,NaN,6,3.833333,NaN,1,NaN
5972,Panty Line,2.8,76,5.10a,"[Trad, TR]",80.0,1,R,NaN,Nevada,...,"['5.8', '5.8', '5.8', '5.11-', '5.10d', '5.5',...",NaN,2.793440,2,7.0,26,0.653846,2.0,1,NaN
5973,Squirt,1.6,13,V0,[Boulder],12.0,1,NaN,NaN,California,...,"['V-easy', 'V4', 'V-easy']",NaN,1.649632,2,NaN,3,0.666667,NaN,1,NaN
5974,Battered Men Shelter,0.5,2,V0,[Boulder],15.0,1,NaN,NaN,California,...,"['V5', 'V1', 'V1+', 'V4', 'V6', 'V1']",NaN,1.098285,2,NaN,6,3.000000,NaN,1,NaN
5975,Gobs of Knobs,1.0,1,5.11,[TR],200.0,1,NaN,NaN,California,...,"['5.10', '5.10c', '5.10b/c', '5.10d', '5.10b',...",NaN,1.647427,5,11.0,16,1.937500,NaN,1,NaN
5976,The Blade,1.0,1,5.12-,"[Trad, TR]",30.0,1,NaN,NaN,California,...,"['5.10d', '5.11c', '5.10c']",NaN,1.647427,6,15.0,3,2.333333,NaN,1,NaN
5977,Another Unnamed V3,3.0,1,V3,[Boulder],10.0,1,NaN,NaN,California,...,[],NaN,2.647427,5,NaN,0,NaN,NaN,1,NaN
5978,Warm-Down,1.0,4,V-easy,[Boulder],10.0,1,R,NaN,California,...,"['V0', 'V4', 'V6', 'V3', 'V5', 'V-easy']",NaN,1.258971,1,NaN,6,3.833333,2.0,1,NaN
5979,Pocket Wall,2.7,6,V0,[Boulder],12.0,1,NaN,NaN,California,...,"['V0', 'V3', 'V0', 'V4', 'V0', 'V1', 'V0', 'V0...",NaN,2.642122,2,NaN,10,1.000000,NaN,1,NaN
5980,Sharp shells,2.0,1,V3,[Boulder],12.0,1,NaN,NaN,Nevada,...,['V4-'],NaN,2.147427,5,NaN,1,1.000000,NaN,1,NaN
5981,Ultraman,3.0,103,5.8+,[Sport],130.0,1,R,NaN,Nevada,...,"['5.9', '5.10-', '5.7', '5.6', '5.9', '5.7+', ...",NaN,2.993220,2,5.0,13,0.153846,2.0,1,NaN
5982,F-22 Raptor,1.0,1,5.7,[Trad],65.0,1,NaN,NaN,Nevada,...,"['5.10c/d', '5.8+', '5.10a', '5.9', '5.7', '5....",NaN,1.647427,2,4.0,24,0.000000,NaN,1,NaN
5983,Handbone,3.2,59,5.10,[Trad],70.0,1,NaN,NaN,Nevada,...,"['5.11', '5.10a', '5.10+', '5.12a', '5.11a', '...",NaN,3.184914,3,7.0,15,1.466667,NaN,1,NaN

In [24]:
df.aid_grade.unique()

array([nan, 'A4', 'A3', 'A3+', 'A0', 'A2+', 'A2', 'A4-', 'A1', 'A1+',
       'A4+', 'A3-', 'A1-2', 'A5+', 'A2-3', 'A4-5', 'A1-', 'A0-1', 'A0+',
       'A2-', 'A5'], dtype=object)

In [25]:
#Save it as a csv file
df.to_csv('pre_processed.csv')

In [26]:
#Split into 80-20 training data and test data.
eighty_percent = int(len(df.index)*.8)
train = df.iloc[:eighty_percent]
test = df.iloc[eighty_percent:]
print("Shape of new dataframes - {} , {}".format(train.shape, test.shape)) 

train.to_csv('train_data.csv')
test.to_csv('test_data.csv')

Shape of new dataframes - (4181, 23) , (1046, 23)

In [27]:
#Create separate a separate csv file for sport routes
sport = df.copy()

def find_sport(row):
    """Drops rows that aren't purely sport routes."""
    row_type = row['type']
    if (len(row_type) == 1) and (row_type[0] == 'Sport'):
        count = 0
    else:
        sport.drop(index = row.name, inplace = True)

sport.apply(lambda row: find_sport(row), axis = 1)
sport.to_csv('sport_routes.csv')

In [28]:
#Create separate a separate csv file for boulder routes
boulder = df.copy()

def find_boulder(row):
    """Drops rows that aren't purely boulder routes."""
    row_type = row['type']
    if (len(row_type) == 1) and (row_type[0] == 'Boulder'):
        count = 0
    else:
        boulder.drop(index = row.name, inplace = True)

boulder.apply(lambda row: find_boulder(row), axis = 1)
boulder.to_csv('boulder_routes.csv')

In [29]:
#Create separate a separate csv file for trad routes
trad = df.copy()

def find_trad(row):
    """Drops rows that aren't purely trad routes."""
    row_type = row['type']
    if (len(row_type) == 1) and (row_type[0] == 'Trad'):
        count = 0
    else:
        trad.drop(index = row.name, inplace = True)

trad.apply(lambda row: find_trad(row), axis = 1)
trad.to_csv('trad_routes.csv')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5227 entries, 0 to 5983
Data columns (total 23 columns):
name                     5227 non-null object
rating                   5227 non-null float64
votes                    5227 non-null int64
grade                    5227 non-null object
type                     5227 non-null object
height                   5227 non-null float64
pitches                  5227 non-null int64
safety                   666 non-null object
commitment               354 non-null object
state                    5227 non-null object
sub_area                 5227 non-null object
photos                   5227 non-null int64
comments                 5227 non-null int64
near_grades              5227 non-null object
aid_grade                143 non-null object
popularity               5227 non-null float64
combined_difficulty      5227 non-null int64
difficulty_sport_trad    3243 non-null float64
number_near_grades       5227 non-null int64
diff_nearby_grades       4970 non-null float64
safety_numerical         666 non-null float64
commitment_numerical     5227 non-null int64
aid_numerical            143 non-null float64
dtypes: float64(7), int64(7), object(9)
memory usage: 980.1+ KB